apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-ttt
  namespace: services
  labels:
    app: multi-ttt
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: multi-ttt
  template:
    metadata:
      labels:
        app: multi-ttt
    spec:
      containers:
        - name: multi-ttt
          image: plamencode/multi-ttt:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10