apiVersion: v1
kind: Service
metadata:
  name: devops-site
  namespace: services
spec:
  selector:
    app: devops-site
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
