apiVersion: v1
kind: Service
metadata:
  name: flappy-birds
  namespace: services
spec:
  selector:
    app: flappy-birds
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
