apiVersion: v1
kind: Service
metadata:
  name: multi-ttt
  namespace: services
  labels:
    app: multi-ttt
spec:
  type: ClusterIP
  selector:
    app: multi-ttt
  ports:
    - name: http
      port: 80
      targetPort: 3000