apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-ttt
  namespace: services
  labels:
    app: multi-ttt
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: multi-ttt
  template:
    metadata:
      labels:
        app: multi-ttt
    spec:
      containers:
        - name: multi-ttt
          image: plamencode/multi-ttt:3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10