apiVersion: v1
kind: Service
metadata:
  name: tik-tak-toe
  namespace: services
spec:
  selector:
    app: tik-tak-toe
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
