apiVersion: v1
kind: Service
metadata:
  name: wach-a-mole
  namespace: services
spec:
  selector:
    app: wach-a-mole
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
